push:   true
override: true
delete_pattern: tmp-${group1}.*-(2[0-9]{7,})
expires_days: 7
daily: d$${now.strftime("%Y%m%d")}
architecture: ${group1}
test:
  script: test-cmssw.sh
  node:   singularity
variables:
  CI_TESTS: stageout
  DEFAULT_PACKAGES: coreutils-single
  BUILD_DATE: $${now.strftime("%Y%m%d-%H%M%S")}
  EPEL_PACKAGES:
groups:
  runtime:
    docker: Dockerfile.${group0}
    from: ${container}:${group1}
    variables:
      SKIP_TESTS: true
    groups:
      x86_64:
        tags:
          ${group1}-${group0}:
  latest:
    alias: ${group1}-${daily}
    from: library/almalinux:8
    groups:
      x86_64:
        variables:
          EXTRA_COMMAND: dnf --enablerepo=powertools install -y doxygen
        tags:
          ${group1}:
